# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install -g firebase-tools
    - name: Run Tests
      env:
        FIREBASE_PROJECT_ID: "osintagram-be0cd"
        FIREBASE_CLIENT_EMAIL: "firebase-adminsdk-9l3nc@osintagram-be0cd.iam.gserviceaccount.com"
        FIREBASE_PRIVATE_KEY:  ${{ secrets.FIREBASE_PRIVATE_KEY }}
      run: |
        echo "$FIREBASE_PRIVATE_KEY" | base64 --decode > $HOME/firebase_key.json
        firebase auth:ci --project=$FIREBASE_PROJECT_ID --token="${{ secrets.FIREBASE_TOKEN }}"
        firebase use $FIREBASE_PROJECT_ID --token="${{ secrets.FIREBASE_TOKEN }}"
        firebase functions:config:get > $firebase.json
        jest
    - run: npm ci
    - run: npm test
